version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb_network
    ports:
      - 
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    volumes:
      - mongodb-data
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://@localhost:port || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - mysql:/var/lib/mysql
    restart: always
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    ports:
      - 
      -
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
  rancher:
    container_name: rancher
    image: rancher/rancher
    privileged: true
    ports:
      - 
      -
    restart: always
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      -
    restart: always
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    depends_on:
      - mysql
    ports:
      - 
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - nextcloud:/var/www/html
    restart: always
  backend:
    container_name: upgraded-disco
    image: upgraded-disco
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 
    restart: always
  portfolio:
    container_name: portfolio
    image: portfolio
    depends_on:
      - backend
    ports:
      - 
    restart: always
    
volumes:
  mongodb-data:
    name: mongodb-data
  mysql:
  nextcloud:
  portainer_data:
networks:
  mongodb_network:
    name: mongodb_network
