version: "3.8"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    restart: always
    networks:
      - common
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - common
    ports:
      - 27017:27017
    restart: always
  mongo-express:
    image: mongo-express
    container_name: express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    networks:
      - common
    ports:
      - 8082:8081
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    networks:
      - common
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
      - 33060:33060
  
volumes:
  mongodb-data:
    name: mongodb-data
  portainer_data:
  mysql:

networks:
  common:
    name: common